#!/bin/sh
set -eu

TEMPLATE_PATH="/usr/share/nginx/html/runtime-config.template.js"
OUTPUT_PATH="/usr/share/nginx/html/runtime-config.js"

if [ ! -f "$TEMPLATE_PATH" ]; then
  echo "Runtime config template missing at $TEMPLATE_PATH"
  exit 1
fi

VITE_BACKEND_URL="${VITE_BACKEND_URL:-}"
VITE_GOOGLE_CLIENT_ID="${VITE_GOOGLE_CLIENT_ID:-}"
VITE_STUN_URLS="${VITE_STUN_URLS:-}"
VITE_TURN_URLS="${VITE_TURN_URLS:-}"
VITE_TURN_USERNAME="${VITE_TURN_USERNAME:-}"
VITE_TURN_CREDENTIAL="${VITE_TURN_CREDENTIAL:-}"
VITE_WEBRTC_ICE_SERVERS="${VITE_WEBRTC_ICE_SERVERS:-}"
VITE_GIPHY_API_KEY="${VITE_GIPHY_API_KEY:-}"

envsubst '${VITE_BACKEND_URL} ${VITE_GOOGLE_CLIENT_ID} ${VITE_STUN_URLS} ${VITE_TURN_URLS} ${VITE_TURN_USERNAME} ${VITE_TURN_CREDENTIAL} ${VITE_WEBRTC_ICE_SERVERS} ${VITE_GIPHY_API_KEY}' < "$TEMPLATE_PATH" > "$OUTPUT_PATH"
